---
- name: Install any necessary dependencies [RedHat/CentOS]
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - curl
  tags: install-influxdb

- name: Install any necessary PIP dependencies [RedHat/CentOS]
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - python-pip
  when: influxdb_install_python_client
  tags: install-influxdb

- name: Add InfluxData repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdata.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: yes
    backup: yes
  when: influxdb_install_url is not defined or influxdb_install_url == None
  tags: install-influxdb

- name: Install InfluxDB packages [RHEL/CentOS]
  yum: 
    name: influxdb
    state: latest
  when: influxdb_install_url is not defined or influxdb_install_url == None
  notify:
  	- "restart influxdb"
  tags: install-influxdb

- name: Install InfluxDB from URL [RHEL/CentOS]
  yum: 
    name: "{{ influxdb_install_url }}"
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None
  notify:
  	- "restart influxdb"
  tags: install-influxdb  

