---
# install grafana-server on ubuntu 16.04

- name: add apt-transport-https
  apt: name=apt-transport-https state=present
  tags: install-grafana

- name: add grafana-apt-repository
  apt_repository: repo='deb https://packages.grafana.com/enterprise/deb stable main' state=present
  tags: install-grafana

- name: add package key
  apt_key: url=https://packages.grafana.com/gpg.key state=present
  tags: install-grafana

- name: update apt cache
  apt: update_cache=yes
  tags: install-grafana

- name: install grafana
  apt: name=grafana state=latest
  notify:
      - restart grafana
  tags: install-grafana

- name: configure grafana server start at boot
  systemd:
    state: started
    name: grafana-server
  tags: install-grafana

