---
# Channel of InfluxDB to install (stable, unstable, nightly)
influxdb_install_version: stable

# If multiple servers are specified, whether to create a clustered configuration
# NOTE:
#   - Do not attempt to cluster previously-unclustered servers. This can lead to data loss.
#   - This will overwrite your /etc/default/influxdb file (though it makes a backup)
influxdb_cluster_servers: no
# When clustering is enabled, whether or not to overwrite the /etc/hosts file with raw
# IPs (may be useful if no DNS resolution).
influxdb_overwrite_hosts_file: no

# Whether to load sample data (randomly generated integers) into a test database
# NOTE: sample data cannot be loaded if authentication is enabled
influxdb_load_sample_data: no
influxdb_sample_database_name: sample_database
influxdb_sample_measurement_name: random_ints

influxdb_bind_hostname: ''

influxdb_install_python_client: no

# NOTE: Since Ansible uses Python on the backend, all boolean values are capitalized when being
# rendered (which is not valid TOML). To get around this, make sure you quote any boolean values
# (true -> "true") to ensure correct formatting (for template variables).

# InfluxDB configuration file options
influxdb_disable_reporting: "false"

influxdb_configuration_dir: /etc/influxdb

## Meta Settings
influxdb_meta_enabled: "true"
influxdb_meta_dir: /var/lib/influxdb/meta
influxdb_meta_hostname: 
influxdb_meta_port: 8088
influxdb_meta_http_port: 8091
influxdb_meta_retention_autocreate: "true"
influxdb_meta_election_timeout: 1s
influxdb_meta_heartbeat_timeout: 1s
influxdb_meta_leader_lease_timeout: 500ms
influxdb_meta_commit_timeout: 50ms
influxdb_meta_cluster_tracing: "false"

## Data Settings
influxdb_data_enabled: "true"
influxdb_data_dir: /var/lib/influxdb/data
influxdb_data_engine: "tsm1"
influxdb_data_query_log_enabled: "true"
influxdb_data_max_wal_size: 104857600
influxdb_data_wal_flush_interval: 10m0s
influxdb_data_wal_partition_flush_delay: 2s
influxdb_data_wal_dir: /var/lib/influxdb/wal
influxdb_data_wal_logging_enabled: "true"
influxdb_data_wal_ready_series_size: 30720
influxdb_data_wal_compaction_threshold: 0.5
influxdb_data_wal_max_series_size: 1048576
influxdb_data_wal_flush_cold_interval: 5s
influxdb_data_wal_partition_size_threshold: 20971520

## Cluster Settings
influxdb_cluster_shard_writer_timeout: 5s
influxdb_cluster_force_remote_mapping: "false"
influxdb_cluster_write_timeout: 5s
influxdb_cluster_shard_mapper_timeout: 5s

## Retention Settings
influxdb_retention_enabled: "true"
influxdb_retention_check_interval: 30m0s

# Shard-Precreation Settings
influxdb_shard_pre_enabled: "true"
influxdb_shard_pre_check_interval: 10m0s
influxdb_shard_pre_advance_period: 30m0s

## Admin Settings
influxdb_admin_enabled: "true"
influxdb_admin_port: 8083
influxdb_admin_https_enabled: "false"
influxdb_admin_https_certificate: /etc/ssl/influxdb.pem

## Monitor Settings (not to be confused with 'Monitoring')
influxdb_monitor_store_enabled: "true"
influxdb_monitor_store_database: _internal
influxdb_monitor_store_interval: 10s

## HTTP Settings
influxdb_http_enabled: "true"
influxdb_http_port: 8086
influxdb_http_auth_enabled: "false"
influxdb_http_log_enabled: "true"
influxdb_http_write_tracing: "false"
influxdb_http_pprof_enabled: "false"
influxdb_http_https_enabled: "false"
influxdb_http_https_certificate: /etc/ssl/influxdb.pem
influxdb_http_https_certificate_key: /etc/ssl/influxdb_key.pem

## Graphite Settings
influxdb_graphite_enabled: "false"
influxdb_graphite_port: 2003
influxdb_graphite_protocol: tcp
influxdb_graphite_consistency_level: one
influxdb_graphite_name_separator: .
influxdb_graphite_name_position: last
influxdb_graphite_batch_size: 1000
influxdb_graphite_batch_pending: 5
influxdb_graphite_batch_timeout: 1s
influxdb_graphite_name_schema: type.host.measurement.device
influxdb_graphite_ignore_unnamed: "true"

## Collectd Settings
influxdb_collectd_enabled: "false"
influxdb_collectd_port: 25826
influxdb_collectd_database: collectd
influxdb_collectd_retention_policy: ""
influxdb_collectd_batch_size: 1000
influxdb_collectd_batch_pending: 5
influxdb_collectd_batch_timeout: 10s
influxdb_collectd_typesdb: /usr/share/collectd/types.db

## OpenTSDB Settings
influxdb_opentsdb_enabled: "false"
influxdb_opentsdb_port: 4242
influxdb_opentsdb_database: opentsdb
influxdb_opentsdb_retention_policy: ""
influxdb_opentsdb_consistency_level: one
influxdb_opentsdb_tls_enabled: "false"
influxdb_opentsdb_certificate: /etc/ssl/influxdb.pem
influxdb_opentsdb_batch_size: 1000
influxdb_opentsdb_batch_pending: 5
influxdb_opentsdb_batch_timeout: 1s

## UDP Settings
influxdb_udp_enabled: "false"
influxdb_udp_bind_address: ""
influxdb_udp_database: ""
influxdb_udp_batch_size: 0
influxdb_udp_batch_timeout: 0

## Monitoring Settings
influxdb_monitoring_enabled: "true"
influxdb_monitoring_write_interval: 24h

## Continuous Queries Settings
influxdb_cq_log_enabled: "true"
influxdb_cq_enabled: "true"
influxdb_cq_recompute_previous_n: 2
influxdb_cq_recompute_no_older_than: 10m
influxdb_cq_compute_runs_per_interval: 10
influxdb_cq_compute_no_more_than: 2m

## Hinted-Handoff Settings
influxdb_hh_enabled: "true"
influxdb_hh_dir: /var/lib/influxdb/hh
influxdb_hh_max_size: 1073741824
influxdb_hh_max_age: 168h
influxdb_hh_retry_rate_limit: 0
influxdb_hh_retry_interval: 1s
influxdb_hh_purge_interval: 1h

# Channel of Telegraf to install
telegraf_install_version: stable

# The user and group telegraf should run under (should be set to telegraf unless needed otherwise)
telegraf_runas_user: telegraf
telegraf_runas_group: telegraf

# Configuration Template
telegraf_configuration_template: telegraf.conf.j2

# Configuration Variables
telegraf_tags:
telegraf_aws_tags: false
telegraf_aws_tags_prefix:

telegraf_agent_interval: 10s
telegraf_round_interval: "true"
telegraf_metric_batch_size: "1000"
telegraf_metric_buffer_limit: "10000"

telegraf_collection_jitter: 0s
telegraf_flush_interval: 10s
telegraf_flush_jitter: 0s
telegraf_debug: "false"
telegraf_quiet: "false"
telegraf_hostname:
telegraf_omit_hostname: "false"
telegraf_install_url:

telegraf_influxdb_urls:
  - http://localhost:8086
telegraf_influxdb_database: telegraf
telegraf_influxdb_precision: s
telegraf_influxdb_retention_policy: autogen
telegraf_influxdb_write_consistency: any
telegraf_influxdb_ssl_ca:
telegraf_influxdb_ssl_cert:
telegraf_influxdb_ssl_key:
telegraf_influxdb_insecure_skip_verify:

telegraf_influxdb_timeout: 5s
telegraf_influxdb_username:
telegraf_influxdb_password:
telegraf_influxdb_user_agent:
telegraf_influxdb_udp_payload:

telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      fielddrop:
        - "time_*"
  - name: disk
    options:
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: procstat
    options:
      exe: "influxd"
      prefix: "influxdb"
  - name: net
    options:
      interfaces:
        - "eth0"

telegraf_plugins: "{{ telegraf_plugins_base }} + {{ telegraf_plugins_extra | default([]) }}"

telegraf_influxdata_base_url: "https://repos.influxdata.com"


#### iptables variables ##################

firewall_state: started
firewall_enabled_at_boot: true

firewall_flush_rules_and_chains: true

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "3000"
  - "8086"

firewall_allowed_udp_ports: []
firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []
firewall_additional_rules: []
firewall_enable_ipv6: true
firewall_ip6_additional_rules: []
firewall_log_dropped_packets: true

# Set to true to ensure other firewall management software is disabled.
firewall_disable_firewalld: false
firewall_disable_ufw: false