---
# copy telegraf.conf to all hosts
- hosts: cen7-server
  become: yes
  tasks:
  - name: copy telegraf conf all host
    template:
      src: telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
      force: yes
      backup: yes
      owner: telegraf
      group: telegraf
      mode: 0744
    tags: copy-telegraf-config

  - name: Restarted telegraf service
    service:
       name: telegraf
       state: restarted
    tags: copy-telegraf-config


