---
# install telegraf on ubuntu 16.04

- name: install any dependencies on Debian
  apt:
    name:
       - python-httplib2
       - python-apt
       - curl
       - apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 3600
	tags: install-telegraf

- name: Import influxdata GPG key Debian
  apt_key: 
    url: "{{ telegraf_influxdata_base_url }}/influxdb.key"
    state: present
  when: telegraf_install_url is not defined or telegraf_install_url == None
  tags: install-telegraf

- name: Add influxdate repository
  apt_repository: 
    repo: deb {{ telegraf_influxdata_base_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ telegraf_install_version }}
    state: present
  when: telegraf_install_url is not defined or telegraf_install_url == None
  tags: install-telegraf

- name: install telegraf on ubuntu
  apt:
    name: telegraf
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  register: apt_result
  until: apt_result is success
  retries: 2
  delay: 5
  when: telegraf_install_url is not defined or telegraf_install_url == None
  notify:
  	- "restart telegraf"
  tags: install-telegraf




              
           
