---
- name: Add InfluxData repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdata.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: yes
    backup: yes
  when: telegraf_install_url is not defined or telegraf_install_url == None
  tags: install-telegraf

- name: Install Telegraf packages [RHEL/CentOS]
  yum:
    name: telegraf
    state: latest
    update_cache: yes
  when: telegraf_install_url is not defined or telegraf_install_url == None
  notify:
      - restart telegraf
  tags: install-telegraf

- name: Install Telegraf from URL [RHEL/CentOS]
  yum:
    name: "{{ telegraf_install_url }}"
    state: present
  when: telegraf_install_url is defined and telegraf_install_url != None
  notify:
      - restart telegraf
  tags: install-telegraf

- name: copy telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    force: yes
    backup: yes
    owner: telegraf
    group: telegraf
    mode: 0744
  notify:
    - restart telegraf
  tags: install-telegraf









